// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Server sends acknowledgement
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// ListOfString is a list of strings
type ListOfString struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfString) Reset()         { *m = ListOfString{} }
func (m *ListOfString) String() string { return proto.CompactTextString(m) }
func (*ListOfString) ProtoMessage()    {}
func (*ListOfString) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{1}
}
func (m *ListOfString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfString.Unmarshal(m, b)
}
func (m *ListOfString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfString.Marshal(b, m, deterministic)
}
func (dst *ListOfString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfString.Merge(dst, src)
}
func (m *ListOfString) XXX_Size() int {
	return xxx_messageInfo_ListOfString.Size(m)
}
func (m *ListOfString) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfString.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfString proto.InternalMessageInfo

func (m *ListOfString) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// EmailRequest is the request to send email. This data is streamed from client
// to the server.
type EmailRequest struct {
	ToEmail              string   `protobuf:"bytes,1,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName               string   `protobuf:"bytes,2,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	FromEmail            string   `protobuf:"bytes,3,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	FromName             string   `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 []byte   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{2}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func (m *EmailRequest) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *EmailRequest) GetFromEmail() string {
	if m != nil {
		return m.FromEmail
	}
	return ""
}

func (m *EmailRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// EmailResponse is the response from the server after email is sent.
type EmailResponse struct {
	StatusCode           int64                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body                 string                   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers              map[string]*ListOfString `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EmailResponse) Reset()         { *m = EmailResponse{} }
func (m *EmailResponse) String() string { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()    {}
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{3}
}
func (m *EmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResponse.Unmarshal(m, b)
}
func (m *EmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResponse.Marshal(b, m, deterministic)
}
func (dst *EmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResponse.Merge(dst, src)
}
func (m *EmailResponse) XXX_Size() int {
	return xxx_messageInfo_EmailResponse.Size(m)
}
func (m *EmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResponse proto.InternalMessageInfo

func (m *EmailResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *EmailResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EmailResponse) GetHeaders() map[string]*ListOfString {
	if m != nil {
		return m.Headers
	}
	return nil
}

// InferImageRequest takes a list of images (as bytes) and model and label file path URIs.
type InferImageRequest struct {
	// List of images
	Images []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// Model name.
	// Model files (.pb and .txt) exist in a folder by this name in
	// designated object store.
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Model version is the version number of the model
	ModelVersion         string   `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InferImageRequest) Reset()         { *m = InferImageRequest{} }
func (m *InferImageRequest) String() string { return proto.CompactTextString(m) }
func (*InferImageRequest) ProtoMessage()    {}
func (*InferImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{4}
}
func (m *InferImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferImageRequest.Unmarshal(m, b)
}
func (m *InferImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferImageRequest.Marshal(b, m, deterministic)
}
func (dst *InferImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferImageRequest.Merge(dst, src)
}
func (m *InferImageRequest) XXX_Size() int {
	return xxx_messageInfo_InferImageRequest.Size(m)
}
func (m *InferImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InferImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InferImageRequest proto.InternalMessageInfo

func (m *InferImageRequest) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *InferImageRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *InferImageRequest) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

// Image consists of a name and bytes
type Image struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{5}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// InferImageResponse is a list of output, one per input image.
type InferImageResponse struct {
	Outputs              []*InferOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InferImageResponse) Reset()         { *m = InferImageResponse{} }
func (m *InferImageResponse) String() string { return proto.CompactTextString(m) }
func (*InferImageResponse) ProtoMessage()    {}
func (*InferImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{6}
}
func (m *InferImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferImageResponse.Unmarshal(m, b)
}
func (m *InferImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferImageResponse.Marshal(b, m, deterministic)
}
func (dst *InferImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferImageResponse.Merge(dst, src)
}
func (m *InferImageResponse) XXX_Size() int {
	return xxx_messageInfo_InferImageResponse.Size(m)
}
func (m *InferImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InferImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InferImageResponse proto.InternalMessageInfo

func (m *InferImageResponse) GetOutputs() []*InferOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// InferOutput consists of a name, inferred label and probability for that label.
type InferOutput struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Probability          int64    `protobuf:"varint,3,opt,name=probability,proto3" json:"probability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InferOutput) Reset()         { *m = InferOutput{} }
func (m *InferOutput) String() string { return proto.CompactTextString(m) }
func (*InferOutput) ProtoMessage()    {}
func (*InferOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{7}
}
func (m *InferOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferOutput.Unmarshal(m, b)
}
func (m *InferOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferOutput.Marshal(b, m, deterministic)
}
func (dst *InferOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferOutput.Merge(dst, src)
}
func (m *InferOutput) XXX_Size() int {
	return xxx_messageInfo_InferOutput.Size(m)
}
func (m *InferOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_InferOutput.DiscardUnknown(m)
}

var xxx_messageInfo_InferOutput proto.InternalMessageInfo

func (m *InferOutput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InferOutput) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *InferOutput) GetProbability() int64 {
	if m != nil {
		return m.Probability
	}
	return 0
}

type GanRequest struct {
	// Model name.
	// Model files (.pb) exist in a folder by this name in
	// designated object store.
	ModelName string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Model version is the version number of the model
	ModelVersion string `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Number of images to generate
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GanRequest) Reset()         { *m = GanRequest{} }
func (m *GanRequest) String() string { return proto.CompactTextString(m) }
func (*GanRequest) ProtoMessage()    {}
func (*GanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{8}
}
func (m *GanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GanRequest.Unmarshal(m, b)
}
func (m *GanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GanRequest.Marshal(b, m, deterministic)
}
func (dst *GanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GanRequest.Merge(dst, src)
}
func (m *GanRequest) XXX_Size() int {
	return xxx_messageInfo_GanRequest.Size(m)
}
func (m *GanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GanRequest proto.InternalMessageInfo

func (m *GanRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *GanRequest) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

func (m *GanRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// InferImageRequest takes a list of images (as bytes) and model and label file path URIs.
type GanResponse struct {
	// List of images
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GanResponse) Reset()         { *m = GanResponse{} }
func (m *GanResponse) String() string { return proto.CompactTextString(m) }
func (*GanResponse) ProtoMessage()    {}
func (*GanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{9}
}
func (m *GanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GanResponse.Unmarshal(m, b)
}
func (m *GanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GanResponse.Marshal(b, m, deterministic)
}
func (dst *GanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GanResponse.Merge(dst, src)
}
func (m *GanResponse) XXX_Size() int {
	return xxx_messageInfo_GanResponse.Size(m)
}
func (m *GanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GanResponse proto.InternalMessageInfo

func (m *GanResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

// Checkpoint is a struct storing weights and biases
type Checkpoint struct {
	// weights stores different weights against a string label
	Weights map[string]*Variable `protobuf:"bytes,1,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// biases stores different biases against a string label
	Biases               map[string]*Variable `protobuf:"bytes,2,rep,name=biases,proto3" json:"biases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{10}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (dst *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(dst, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetWeights() map[string]*Variable {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *Checkpoint) GetBiases() map[string]*Variable {
	if m != nil {
		return m.Biases
	}
	return nil
}

// Variable is basically a buffer and its size
type Variable struct {
	Data                 []float32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Size                 []int64   `protobuf:"varint,2,rep,packed,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{11}
}
func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (dst *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(dst, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Variable) GetSize() []int64 {
	if m != nil {
		return m.Size
	}
	return nil
}

// Data is basically just a byte buffer.
type Data struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{12}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// GalleryRequest is a request to gallery maker. It contains filenames in object store
// that are publicly available.
type GalleryRequest struct {
	GalleryItems         []*GalleryItem `protobuf:"bytes,1,rep,name=gallery_items,json=galleryItems,proto3" json:"gallery_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GalleryRequest) Reset()         { *m = GalleryRequest{} }
func (m *GalleryRequest) String() string { return proto.CompactTextString(m) }
func (*GalleryRequest) ProtoMessage()    {}
func (*GalleryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{13}
}
func (m *GalleryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GalleryRequest.Unmarshal(m, b)
}
func (m *GalleryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GalleryRequest.Marshal(b, m, deterministic)
}
func (dst *GalleryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GalleryRequest.Merge(dst, src)
}
func (m *GalleryRequest) XXX_Size() int {
	return xxx_messageInfo_GalleryRequest.Size(m)
}
func (m *GalleryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GalleryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GalleryRequest proto.InternalMessageInfo

func (m *GalleryRequest) GetGalleryItems() []*GalleryItem {
	if m != nil {
		return m.GalleryItems
	}
	return nil
}

// GalleryItem is a individual items for gallery presentation
type GalleryItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	BucketName           string   `protobuf:"bytes,5,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GalleryItem) Reset()         { *m = GalleryItem{} }
func (m *GalleryItem) String() string { return proto.CompactTextString(m) }
func (*GalleryItem) ProtoMessage()    {}
func (*GalleryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{14}
}
func (m *GalleryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GalleryItem.Unmarshal(m, b)
}
func (m *GalleryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GalleryItem.Marshal(b, m, deterministic)
}
func (dst *GalleryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GalleryItem.Merge(dst, src)
}
func (m *GalleryItem) XXX_Size() int {
	return xxx_messageInfo_GalleryItem.Size(m)
}
func (m *GalleryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GalleryItem.DiscardUnknown(m)
}

var xxx_messageInfo_GalleryItem proto.InternalMessageInfo

func (m *GalleryItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GalleryItem) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *GalleryItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GalleryItem) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *GalleryItem) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

// GalleryResponse is an empty response.
type GalleryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GalleryResponse) Reset()         { *m = GalleryResponse{} }
func (m *GalleryResponse) String() string { return proto.CompactTextString(m) }
func (*GalleryResponse) ProtoMessage()    {}
func (*GalleryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{15}
}
func (m *GalleryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GalleryResponse.Unmarshal(m, b)
}
func (m *GalleryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GalleryResponse.Marshal(b, m, deterministic)
}
func (dst *GalleryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GalleryResponse.Merge(dst, src)
}
func (m *GalleryResponse) XXX_Size() int {
	return xxx_messageInfo_GalleryResponse.Size(m)
}
func (m *GalleryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GalleryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GalleryResponse proto.InternalMessageInfo

// ConfigRequest is a message used to get config parameters
type ConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{16}
}
func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(dst, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

// ConfigResponse is a set of config parameters for lambda functions.
// Currently these are all lumped into one struct but this will
// get divided into sub structs later on.
type ConfigResponse struct {
	// name of lambda function
	FuncName string `protobuf:"bytes,1,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	// code location of lambda function
	CodeLocation string `protobuf:"bytes,2,opt,name=code_location,json=codeLocation,proto3" json:"code_location,omitempty"`
	// domain of lambda function
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// bucket name to use
	BucketName string `protobuf:"bytes,4,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// oauth request to send to various providers
	Oauth *OAuthRequest `protobuf:"bytes,5,opt,name=oauth,proto3" json:"oauth,omitempty"`
	// jwt secret passphrase
	JwtSecret            string   `protobuf:"bytes,6,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{17}
}
func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(dst, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *ConfigResponse) GetCodeLocation() string {
	if m != nil {
		return m.CodeLocation
	}
	return ""
}

func (m *ConfigResponse) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ConfigResponse) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ConfigResponse) GetOauth() *OAuthRequest {
	if m != nil {
		return m.Oauth
	}
	return nil
}

func (m *ConfigResponse) GetJwtSecret() string {
	if m != nil {
		return m.JwtSecret
	}
	return ""
}

// OAuthRequest is a collection of all supported oauth providers
type OAuthRequest struct {
	// Google as oauth provider
	Google               *GoogleOAuthRequest `protobuf:"bytes,1,opt,name=google,proto3" json:"google,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OAuthRequest) Reset()         { *m = OAuthRequest{} }
func (m *OAuthRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthRequest) ProtoMessage()    {}
func (*OAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{18}
}
func (m *OAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthRequest.Unmarshal(m, b)
}
func (m *OAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthRequest.Marshal(b, m, deterministic)
}
func (dst *OAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthRequest.Merge(dst, src)
}
func (m *OAuthRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthRequest.Size(m)
}
func (m *OAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthRequest proto.InternalMessageInfo

func (m *OAuthRequest) GetGoogle() *GoogleOAuthRequest {
	if m != nil {
		return m.Google
	}
	return nil
}

// GoogleOAuthRequest is used to send oauth request to google oauth provider
type GoogleOAuthRequest struct {
	// client id for oauth2
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// client secret for oauth2
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleOAuthRequest) Reset()         { *m = GoogleOAuthRequest{} }
func (m *GoogleOAuthRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleOAuthRequest) ProtoMessage()    {}
func (*GoogleOAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{19}
}
func (m *GoogleOAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleOAuthRequest.Unmarshal(m, b)
}
func (m *GoogleOAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleOAuthRequest.Marshal(b, m, deterministic)
}
func (dst *GoogleOAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleOAuthRequest.Merge(dst, src)
}
func (m *GoogleOAuthRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleOAuthRequest.Size(m)
}
func (m *GoogleOAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleOAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleOAuthRequest proto.InternalMessageInfo

func (m *GoogleOAuthRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GoogleOAuthRequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

// GoogleOAuthResponse is used to deserialize the response from google oauth provider
type GoogleOAuthResponse struct {
	// id of the user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// email of the user
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// verified email of the user
	VerifiedEmail string `protobuf:"bytes,3,opt,name=verified_email,json=verifiedEmail,proto3" json:"verified_email,omitempty"`
	// link of user public profile
	Link string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	// link to user public picture
	Picture              string   `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleOAuthResponse) Reset()         { *m = GoogleOAuthResponse{} }
func (m *GoogleOAuthResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleOAuthResponse) ProtoMessage()    {}
func (*GoogleOAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7c92b552908e29d9, []int{20}
}
func (m *GoogleOAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleOAuthResponse.Unmarshal(m, b)
}
func (m *GoogleOAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleOAuthResponse.Marshal(b, m, deterministic)
}
func (dst *GoogleOAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleOAuthResponse.Merge(dst, src)
}
func (m *GoogleOAuthResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleOAuthResponse.Size(m)
}
func (m *GoogleOAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleOAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleOAuthResponse proto.InternalMessageInfo

func (m *GoogleOAuthResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GoogleOAuthResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GoogleOAuthResponse) GetVerifiedEmail() string {
	if m != nil {
		return m.VerifiedEmail
	}
	return ""
}

func (m *GoogleOAuthResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *GoogleOAuthResponse) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*ListOfString)(nil), "api.ListOfString")
	proto.RegisterType((*EmailRequest)(nil), "api.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "api.EmailResponse")
	proto.RegisterMapType((map[string]*ListOfString)(nil), "api.EmailResponse.HeadersEntry")
	proto.RegisterType((*InferImageRequest)(nil), "api.InferImageRequest")
	proto.RegisterType((*Image)(nil), "api.Image")
	proto.RegisterType((*InferImageResponse)(nil), "api.InferImageResponse")
	proto.RegisterType((*InferOutput)(nil), "api.InferOutput")
	proto.RegisterType((*GanRequest)(nil), "api.GanRequest")
	proto.RegisterType((*GanResponse)(nil), "api.GanResponse")
	proto.RegisterType((*Checkpoint)(nil), "api.Checkpoint")
	proto.RegisterMapType((map[string]*Variable)(nil), "api.Checkpoint.BiasesEntry")
	proto.RegisterMapType((map[string]*Variable)(nil), "api.Checkpoint.WeightsEntry")
	proto.RegisterType((*Variable)(nil), "api.Variable")
	proto.RegisterType((*Data)(nil), "api.Data")
	proto.RegisterType((*GalleryRequest)(nil), "api.GalleryRequest")
	proto.RegisterType((*GalleryItem)(nil), "api.GalleryItem")
	proto.RegisterType((*GalleryResponse)(nil), "api.GalleryResponse")
	proto.RegisterType((*ConfigRequest)(nil), "api.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "api.ConfigResponse")
	proto.RegisterType((*OAuthRequest)(nil), "api.OAuthRequest")
	proto.RegisterType((*GoogleOAuthRequest)(nil), "api.GoogleOAuthRequest")
	proto.RegisterType((*GoogleOAuthResponse)(nil), "api.GoogleOAuthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LambdaClient is the client API for Lambda service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LambdaClient interface {
	// Email service sends email
	Email(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	// InferImage applies trained model on input image for inferring labels
	InferImage(ctx context.Context, opts ...grpc.CallOption) (Lambda_InferImageClient, error)
	// GAN generator
	Gan(ctx context.Context, in *GanRequest, opts ...grpc.CallOption) (Lambda_GanClient, error)
	// Gallery Display of images
	Gallery(ctx context.Context, in *GalleryRequest, opts ...grpc.CallOption) (*GalleryResponse, error)
	// Config fetches config parameters
	Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
}

type lambdaClient struct {
	cc *grpc.ClientConn
}

func NewLambdaClient(cc *grpc.ClientConn) LambdaClient {
	return &lambdaClient{cc}
}

func (c *lambdaClient) Email(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.Lambda/Email", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lambdaClient) InferImage(ctx context.Context, opts ...grpc.CallOption) (Lambda_InferImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lambda_serviceDesc.Streams[0], "/api.Lambda/InferImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &lambdaInferImageClient{stream}
	return x, nil
}

type Lambda_InferImageClient interface {
	Send(*InferImageRequest) error
	CloseAndRecv() (*InferImageResponse, error)
	grpc.ClientStream
}

type lambdaInferImageClient struct {
	grpc.ClientStream
}

func (x *lambdaInferImageClient) Send(m *InferImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lambdaInferImageClient) CloseAndRecv() (*InferImageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InferImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lambdaClient) Gan(ctx context.Context, in *GanRequest, opts ...grpc.CallOption) (Lambda_GanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lambda_serviceDesc.Streams[1], "/api.Lambda/Gan", opts...)
	if err != nil {
		return nil, err
	}
	x := &lambdaGanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lambda_GanClient interface {
	Recv() (*GanResponse, error)
	grpc.ClientStream
}

type lambdaGanClient struct {
	grpc.ClientStream
}

func (x *lambdaGanClient) Recv() (*GanResponse, error) {
	m := new(GanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lambdaClient) Gallery(ctx context.Context, in *GalleryRequest, opts ...grpc.CallOption) (*GalleryResponse, error) {
	out := new(GalleryResponse)
	err := c.cc.Invoke(ctx, "/api.Lambda/Gallery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lambdaClient) Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/api.Lambda/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LambdaServer is the server API for Lambda service.
type LambdaServer interface {
	// Email service sends email
	Email(context.Context, *EmailRequest) (*EmailResponse, error)
	// InferImage applies trained model on input image for inferring labels
	InferImage(Lambda_InferImageServer) error
	// GAN generator
	Gan(*GanRequest, Lambda_GanServer) error
	// Gallery Display of images
	Gallery(context.Context, *GalleryRequest) (*GalleryResponse, error)
	// Config fetches config parameters
	Config(context.Context, *ConfigRequest) (*ConfigResponse, error)
}

func RegisterLambdaServer(s *grpc.Server, srv LambdaServer) {
	s.RegisterService(&_Lambda_serviceDesc, srv)
}

func _Lambda_Email_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).Email(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Lambda/Email",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).Email(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lambda_InferImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LambdaServer).InferImage(&lambdaInferImageServer{stream})
}

type Lambda_InferImageServer interface {
	SendAndClose(*InferImageResponse) error
	Recv() (*InferImageRequest, error)
	grpc.ServerStream
}

type lambdaInferImageServer struct {
	grpc.ServerStream
}

func (x *lambdaInferImageServer) SendAndClose(m *InferImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lambdaInferImageServer) Recv() (*InferImageRequest, error) {
	m := new(InferImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Lambda_Gan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LambdaServer).Gan(m, &lambdaGanServer{stream})
}

type Lambda_GanServer interface {
	Send(*GanResponse) error
	grpc.ServerStream
}

type lambdaGanServer struct {
	grpc.ServerStream
}

func (x *lambdaGanServer) Send(m *GanResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Lambda_Gallery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GalleryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).Gallery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Lambda/Gallery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).Gallery(ctx, req.(*GalleryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lambda_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Lambda/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).Config(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lambda_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Lambda",
	HandlerType: (*LambdaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Email",
			Handler:    _Lambda_Email_Handler,
		},
		{
			MethodName: "Gallery",
			Handler:    _Lambda_Gallery_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Lambda_Config_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InferImage",
			Handler:       _Lambda_InferImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Gan",
			Handler:       _Lambda_Gan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	Query(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Monitor_QueryClient, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) Query(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Monitor_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Monitor_serviceDesc.Streams[0], "/api.Monitor/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Monitor_QueryClient interface {
	Recv() (*Data, error)
	grpc.ClientStream
}

type monitorQueryClient struct {
	grpc.ClientStream
}

func (x *monitorQueryClient) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	Query(*Empty, Monitor_QueryServer) error
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorServer).Query(m, &monitorQueryServer{stream})
}

type Monitor_QueryServer interface {
	Send(*Data) error
	grpc.ServerStream
}

type monitorQueryServer struct {
	grpc.ServerStream
}

func (x *monitorQueryServer) Send(m *Data) error {
	return x.ServerStream.SendMsg(m)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Monitor_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_7c92b552908e29d9) }

var fileDescriptor_api_7c92b552908e29d9 = []byte{
	// 1057 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x71, 0xf3, 0x77, 0x92, 0xf4, 0x67, 0x5a, 0x6d, 0x43, 0x16, 0xb4, 0xd5, 0x2c, 0x88,
	0x0a, 0x2d, 0xdd, 0x25, 0x15, 0x08, 0xb8, 0x81, 0xa5, 0x54, 0xdd, 0x4a, 0xdd, 0xad, 0xf0, 0x4a,
	0x45, 0x5c, 0x45, 0x13, 0x7b, 0x92, 0x4e, 0x6b, 0x7b, 0x8c, 0x3d, 0x6e, 0x15, 0x78, 0x04, 0x24,
	0xc4, 0x25, 0x0f, 0xc1, 0xb3, 0x70, 0xc3, 0x0b, 0xa1, 0x39, 0x33, 0x93, 0xd8, 0x6d, 0x25, 0x90,
	0xb8, 0x9b, 0xf3, 0x9d, 0x9f, 0x39, 0x3f, 0xdf, 0x1c, 0x1b, 0xba, 0x2c, 0x13, 0x07, 0x59, 0x2e,
	0x95, 0x24, 0x3e, 0xcb, 0x04, 0x6d, 0x43, 0xf3, 0x38, 0xc9, 0xd4, 0x82, 0x7e, 0x00, 0xfd, 0x33,
	0x51, 0xa8, 0xf3, 0xd9, 0x5b, 0x95, 0x8b, 0x74, 0x4e, 0x76, 0xa0, 0x79, 0xc3, 0xe2, 0x92, 0x0f,
	0xbd, 0x3d, 0x7f, 0xbf, 0x1b, 0x18, 0x81, 0xfe, 0xe9, 0x41, 0xff, 0x38, 0x61, 0x22, 0x0e, 0xf8,
	0x4f, 0x25, 0x2f, 0x14, 0x79, 0x17, 0x3a, 0x4a, 0x4e, 0xb8, 0x86, 0x86, 0xde, 0x9e, 0xb7, 0xdf,
	0x0d, 0xda, 0x4a, 0xa2, 0x05, 0xd9, 0x85, 0xb6, 0x92, 0x93, 0x94, 0x25, 0x7c, 0xd8, 0x40, 0x4d,
	0x4b, 0xc9, 0x37, 0x2c, 0xe1, 0xe4, 0x7d, 0x80, 0x59, 0x2e, 0x13, 0xeb, 0xe5, 0xa3, 0xae, 0xab,
	0x11, 0xe3, 0xf7, 0x18, 0x50, 0x30, 0x9e, 0x6b, 0xa8, 0xed, 0x68, 0x00, 0x7d, 0x87, 0xd0, 0x2e,
	0xca, 0xe9, 0x15, 0x0f, 0xd5, 0xb0, 0x69, 0xae, 0xb3, 0x22, 0x21, 0xb0, 0x36, 0x95, 0xd1, 0x62,
	0xd8, 0xda, 0xf3, 0xf6, 0xfb, 0x01, 0x9e, 0xe9, 0x5f, 0x1e, 0x0c, 0x6c, 0xba, 0x45, 0x26, 0xd3,
	0x82, 0x93, 0x27, 0xd0, 0x2b, 0x14, 0x53, 0x65, 0x31, 0x09, 0x65, 0xc4, 0x31, 0x65, 0x3f, 0x00,
	0x03, 0x1d, 0xc9, 0x88, 0x2f, 0xc3, 0x98, 0x94, 0xf1, 0x4c, 0xbe, 0x84, 0xf6, 0x25, 0x67, 0x11,
	0xcf, 0x8b, 0xa1, 0xbf, 0xe7, 0xef, 0xf7, 0xc6, 0x4f, 0x0e, 0x74, 0x1b, 0x6b, 0x91, 0x0f, 0x5e,
	0x19, 0x8b, 0xe3, 0x54, 0xe5, 0x8b, 0xc0, 0xd9, 0x8f, 0x5e, 0x43, 0xbf, 0xaa, 0x20, 0x9b, 0xe0,
	0x5f, 0xf3, 0x85, 0x6d, 0x95, 0x3e, 0x92, 0x8f, 0x5c, 0xa3, 0xf5, 0x8d, 0xbd, 0xf1, 0x16, 0x86,
	0xae, 0x8e, 0xc2, 0xf6, 0xfe, 0xab, 0xc6, 0x17, 0x1e, 0xfd, 0x05, 0xb6, 0x4e, 0xd3, 0x19, 0xcf,
	0x4f, 0x13, 0x36, 0xe7, 0x6e, 0x06, 0x14, 0x5a, 0x42, 0xcb, 0x05, 0xce, 0xaa, 0x37, 0x06, 0x0c,
	0x61, 0x4c, 0xac, 0x46, 0xf7, 0x3c, 0x91, 0x11, 0x8f, 0xab, 0xf3, 0xe8, 0x22, 0x82, 0x6d, 0x7d,
	0x0a, 0x03, 0xa3, 0xbe, 0xe1, 0x79, 0x21, 0x64, 0x6a, 0xa7, 0xd2, 0x47, 0xf0, 0xc2, 0x60, 0xf4,
	0x39, 0x34, 0x31, 0xa8, 0xee, 0x11, 0x86, 0x31, 0x55, 0xe0, 0x59, 0x63, 0x11, 0x53, 0x0c, 0x43,
	0xf7, 0x03, 0x3c, 0xd3, 0x6f, 0x80, 0x54, 0xb3, 0xb5, 0x23, 0xf8, 0x18, 0xda, 0xb2, 0x54, 0x59,
	0xa9, 0x5c, 0xbe, 0x9b, 0x26, 0x5f, 0x6d, 0x79, 0x8e, 0x8a, 0xc0, 0x19, 0xd0, 0x1f, 0xa1, 0x57,
	0xc1, 0x1f, 0xbc, 0x78, 0x07, 0x9a, 0x31, 0x9b, 0xf2, 0xd8, 0x16, 0x65, 0x04, 0xb2, 0x07, 0xbd,
	0x2c, 0x97, 0x53, 0x36, 0x15, 0xb1, 0x50, 0x0b, 0x2c, 0xc7, 0x0f, 0xaa, 0x10, 0x9d, 0x01, 0x9c,
	0xb0, 0xd4, 0xf5, 0xb0, 0xde, 0x1f, 0xef, 0x5f, 0xfb, 0xd3, 0xb8, 0xdf, 0x1f, 0x9d, 0x49, 0x28,
	0xcb, 0x54, 0xd9, 0xdb, 0x8c, 0x40, 0x3f, 0x85, 0x1e, 0xde, 0x63, 0xab, 0xff, 0x0f, 0xc3, 0xa2,
	0xbf, 0x35, 0x00, 0x8e, 0x2e, 0x79, 0x78, 0x9d, 0x49, 0x91, 0x2a, 0xf2, 0x39, 0xb4, 0x6f, 0xb9,
	0x98, 0x5f, 0x2e, 0x1b, 0xf6, 0x1e, 0xfa, 0xac, 0x2c, 0x0e, 0x7e, 0x30, 0x6a, 0xcb, 0x3d, 0x6b,
	0x4c, 0x0e, 0xa1, 0x35, 0x15, 0xac, 0xe0, 0xc5, 0xb0, 0x81, 0x6e, 0x8f, 0xef, 0xba, 0x7d, 0x8b,
	0x5a, 0xe3, 0x65, 0x4d, 0x47, 0xa7, 0xd0, 0xaf, 0x46, 0x7b, 0x80, 0xb0, 0x4f, 0xeb, 0x84, 0x1d,
	0x60, 0xd4, 0x0b, 0x96, 0x0b, 0x36, 0x8d, 0x79, 0x85, 0xac, 0xa3, 0x57, 0xd0, 0xab, 0xdc, 0xf0,
	0x3f, 0x22, 0xd1, 0x31, 0x74, 0x1c, 0xbc, 0x24, 0x9a, 0x6e, 0x45, 0xc3, 0x10, 0x4d, 0x63, 0x85,
	0xf8, 0x99, 0x63, 0x9d, 0x7e, 0x80, 0x67, 0xfa, 0x0c, 0xd6, 0xbe, 0xd3, 0xba, 0x4d, 0xf0, 0x15,
	0x9b, 0xbb, 0x6b, 0x15, 0x9b, 0x3f, 0x48, 0xd5, 0x13, 0x58, 0x3f, 0x61, 0x71, 0xcc, 0xf3, 0x85,
	0x63, 0xc4, 0x67, 0x30, 0x98, 0x1b, 0x64, 0x22, 0x14, 0x4f, 0xea, 0x64, 0xb5, 0xb6, 0xa7, 0x8a,
	0x27, 0x41, 0x7f, 0xbe, 0x12, 0x0a, 0xfa, 0xab, 0xa7, 0xe7, 0xbd, 0x04, 0xc8, 0x3a, 0x34, 0x44,
	0x64, 0xf7, 0x4c, 0x43, 0x44, 0xb8, 0xdd, 0x44, 0xcc, 0xab, 0xef, 0xb0, 0xa3, 0x81, 0x37, 0x96,
	0xcb, 0x4a, 0xa8, 0x98, 0xdb, 0xe7, 0x67, 0x04, 0xbd, 0xf3, 0x42, 0x96, 0x29, 0x4d, 0x3b, 0xb3,
	0x0e, 0x9d, 0xa8, 0xb7, 0xd9, 0xb4, 0x0c, 0xaf, 0xb9, 0x32, 0xe1, 0xcc, 0x46, 0x04, 0x03, 0xe9,
	0x80, 0x74, 0x0b, 0x36, 0x96, 0x65, 0x19, 0x02, 0xd2, 0x0d, 0x18, 0x1c, 0xc9, 0x74, 0x26, 0xe6,
	0xb6, 0x50, 0xfa, 0xb7, 0x07, 0xeb, 0x0e, 0xb1, 0x24, 0xd5, 0x49, 0x96, 0x69, 0x58, 0x7d, 0x0c,
	0x1d, 0x0d, 0xb8, 0xb7, 0xa0, 0x77, 0xe7, 0x24, 0x96, 0x21, 0x53, 0x95, 0xb7, 0xa0, 0xc1, 0x33,
	0x8b, 0x91, 0x47, 0xd0, 0x8a, 0x64, 0xc2, 0x84, 0xdb, 0x24, 0x56, 0xba, 0x9b, 0xf1, 0xda, 0xdd,
	0x8c, 0xf5, 0x3a, 0x94, 0xac, 0x54, 0x97, 0x58, 0x8c, 0x5b, 0x87, 0xe7, 0x2f, 0x4b, 0x75, 0x69,
	0xf3, 0x0d, 0x8c, 0x5e, 0xbf, 0xd8, 0xab, 0x5b, 0x35, 0x29, 0x78, 0x98, 0x73, 0x85, 0x5b, 0xbf,
	0x1b, 0x74, 0xaf, 0x6e, 0xd5, 0x5b, 0x04, 0xe8, 0xd7, 0xd0, 0xaf, 0x7a, 0x91, 0xe7, 0xd0, 0x9a,
	0x4b, 0x39, 0x8f, 0x4d, 0x3d, 0xbd, 0xf1, 0xae, 0x99, 0x23, 0x42, 0xb5, 0xf0, 0xd6, 0x8c, 0x5e,
	0x00, 0xb9, 0xaf, 0xd5, 0x9d, 0x09, 0x63, 0xc1, 0x53, 0x35, 0xb1, 0x53, 0xed, 0x06, 0x1d, 0x03,
	0x9c, 0x46, 0xd8, 0x19, 0xa3, 0xb4, 0x59, 0xb9, 0xce, 0x20, 0x68, 0x13, 0xfb, 0xdd, 0x83, 0xed,
	0x5a, 0x60, 0xdb, 0xf3, 0x15, 0x51, 0xba, 0x48, 0x94, 0x1d, 0x68, 0x9a, 0x0f, 0xa4, 0xdd, 0x6b,
	0x28, 0x90, 0x0f, 0x61, 0xfd, 0x86, 0xe7, 0x62, 0x26, 0x78, 0x54, 0xfb, 0x7e, 0x0e, 0x1c, 0x6a,
	0xbe, 0xa1, 0x04, 0xd6, 0x62, 0x91, 0x5e, 0xdb, 0xfe, 0xe2, 0x59, 0xd3, 0x28, 0x13, 0xa1, 0x2a,
	0x73, 0x47, 0x14, 0x27, 0x8e, 0xff, 0x68, 0x40, 0xeb, 0x8c, 0x25, 0xd3, 0x88, 0x91, 0x17, 0xfa,
	0x7f, 0x40, 0x47, 0xd8, 0xaa, 0x7e, 0xe2, 0xb0, 0xf6, 0x11, 0xb9, 0xff, 0xd5, 0xa3, 0xef, 0x90,
	0x97, 0x00, 0xab, 0x25, 0x4f, 0x1e, 0xad, 0x76, 0x79, 0xf5, 0x1b, 0x35, 0xda, 0xbd, 0x87, 0xbb,
	0x00, 0xfb, 0x1e, 0x79, 0x06, 0xfe, 0x09, 0x4b, 0xc9, 0x86, 0x7d, 0x5a, 0x6e, 0x29, 0x8f, 0x36,
	0x57, 0x80, 0xb3, 0x7e, 0xe1, 0xe9, 0x75, 0x68, 0x39, 0x4d, 0xb6, 0xab, 0x8f, 0xd1, 0x79, 0xed,
	0xd4, 0xc1, 0x65, 0xa2, 0x87, 0xd0, 0x32, 0x34, 0x27, 0xa6, 0x90, 0xda, 0x2b, 0x18, 0x6d, 0xd7,
	0x30, 0xe7, 0x34, 0xfe, 0x04, 0xda, 0xaf, 0x65, 0x2a, 0x94, 0xcc, 0x09, 0x85, 0xe6, 0xf7, 0xa5,
	0xbe, 0x15, 0x6c, 0x1f, 0x32, 0xb5, 0x18, 0x75, 0xf1, 0xac, 0x17, 0x8d, 0xce, 0x6d, 0xda, 0xc2,
	0x5f, 0xab, 0xc3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x98, 0x65, 0x12, 0x08, 0x67, 0x09, 0x00,
	0x00,
}
