// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EmailRequest is the request to send email. This data is streamed from client
// to the server.
type EmailRequest struct {
	ToEmail              string   `protobuf:"bytes,1,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName               string   `protobuf:"bytes,2,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	FromEmail            string   `protobuf:"bytes,3,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	FromName             string   `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 []byte   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{0}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func (m *EmailRequest) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *EmailRequest) GetFromEmail() string {
	if m != nil {
		return m.FromEmail
	}
	return ""
}

func (m *EmailRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// SendResponse is the response from the server after email is sent.
type EmailResponse struct {
	StatusCode           int64                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body                 string                   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers              map[string]*ListOfString `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EmailResponse) Reset()         { *m = EmailResponse{} }
func (m *EmailResponse) String() string { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()    {}
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{1}
}
func (m *EmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResponse.Unmarshal(m, b)
}
func (m *EmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResponse.Marshal(b, m, deterministic)
}
func (dst *EmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResponse.Merge(dst, src)
}
func (m *EmailResponse) XXX_Size() int {
	return xxx_messageInfo_EmailResponse.Size(m)
}
func (m *EmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResponse proto.InternalMessageInfo

func (m *EmailResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *EmailResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EmailResponse) GetHeaders() map[string]*ListOfString {
	if m != nil {
		return m.Headers
	}
	return nil
}

// ListOfString is a list of strings
type ListOfString struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfString) Reset()         { *m = ListOfString{} }
func (m *ListOfString) String() string { return proto.CompactTextString(m) }
func (*ListOfString) ProtoMessage()    {}
func (*ListOfString) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{2}
}
func (m *ListOfString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfString.Unmarshal(m, b)
}
func (m *ListOfString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfString.Marshal(b, m, deterministic)
}
func (dst *ListOfString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfString.Merge(dst, src)
}
func (m *ListOfString) XXX_Size() int {
	return xxx_messageInfo_ListOfString.Size(m)
}
func (m *ListOfString) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfString.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfString proto.InternalMessageInfo

func (m *ListOfString) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// InferImageRequest takes a list of images (as bytes) and model and label file path URIs.
type InferImageRequest struct {
	// List of images
	Images []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// Model name.
	// Model files (.pb and .txt) exist in a folder by this name in
	// designated object store.
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Model version is the version number of the model
	ModelVersion         string   `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InferImageRequest) Reset()         { *m = InferImageRequest{} }
func (m *InferImageRequest) String() string { return proto.CompactTextString(m) }
func (*InferImageRequest) ProtoMessage()    {}
func (*InferImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{3}
}
func (m *InferImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferImageRequest.Unmarshal(m, b)
}
func (m *InferImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferImageRequest.Marshal(b, m, deterministic)
}
func (dst *InferImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferImageRequest.Merge(dst, src)
}
func (m *InferImageRequest) XXX_Size() int {
	return xxx_messageInfo_InferImageRequest.Size(m)
}
func (m *InferImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InferImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InferImageRequest proto.InternalMessageInfo

func (m *InferImageRequest) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *InferImageRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *InferImageRequest) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

// Image consists of a name and bytes
type Image struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{4}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// InferImageResponse is a list of output, one per input image.
type InferImageResponse struct {
	Outputs              []*InferOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InferImageResponse) Reset()         { *m = InferImageResponse{} }
func (m *InferImageResponse) String() string { return proto.CompactTextString(m) }
func (*InferImageResponse) ProtoMessage()    {}
func (*InferImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{5}
}
func (m *InferImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferImageResponse.Unmarshal(m, b)
}
func (m *InferImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferImageResponse.Marshal(b, m, deterministic)
}
func (dst *InferImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferImageResponse.Merge(dst, src)
}
func (m *InferImageResponse) XXX_Size() int {
	return xxx_messageInfo_InferImageResponse.Size(m)
}
func (m *InferImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InferImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InferImageResponse proto.InternalMessageInfo

func (m *InferImageResponse) GetOutputs() []*InferOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// InferOutput consists of a name, inferred label and probability for that label.
type InferOutput struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Probability          int64    `protobuf:"varint,3,opt,name=probability,proto3" json:"probability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InferOutput) Reset()         { *m = InferOutput{} }
func (m *InferOutput) String() string { return proto.CompactTextString(m) }
func (*InferOutput) ProtoMessage()    {}
func (*InferOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{6}
}
func (m *InferOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferOutput.Unmarshal(m, b)
}
func (m *InferOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferOutput.Marshal(b, m, deterministic)
}
func (dst *InferOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferOutput.Merge(dst, src)
}
func (m *InferOutput) XXX_Size() int {
	return xxx_messageInfo_InferOutput.Size(m)
}
func (m *InferOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_InferOutput.DiscardUnknown(m)
}

var xxx_messageInfo_InferOutput proto.InternalMessageInfo

func (m *InferOutput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InferOutput) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *InferOutput) GetProbability() int64 {
	if m != nil {
		return m.Probability
	}
	return 0
}

type GanRequest struct {
	// Model name.
	// Model files (.pb) exist in a folder by this name in
	// designated object store.
	ModelName string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Model version is the version number of the model
	ModelVersion string `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Number of images to generate
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GanRequest) Reset()         { *m = GanRequest{} }
func (m *GanRequest) String() string { return proto.CompactTextString(m) }
func (*GanRequest) ProtoMessage()    {}
func (*GanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{7}
}
func (m *GanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GanRequest.Unmarshal(m, b)
}
func (m *GanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GanRequest.Marshal(b, m, deterministic)
}
func (dst *GanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GanRequest.Merge(dst, src)
}
func (m *GanRequest) XXX_Size() int {
	return xxx_messageInfo_GanRequest.Size(m)
}
func (m *GanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GanRequest proto.InternalMessageInfo

func (m *GanRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *GanRequest) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

func (m *GanRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// InferImageRequest takes a list of images (as bytes) and model and label file path URIs.
type GanResponse struct {
	// List of images
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GanResponse) Reset()         { *m = GanResponse{} }
func (m *GanResponse) String() string { return proto.CompactTextString(m) }
func (*GanResponse) ProtoMessage()    {}
func (*GanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{8}
}
func (m *GanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GanResponse.Unmarshal(m, b)
}
func (m *GanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GanResponse.Marshal(b, m, deterministic)
}
func (dst *GanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GanResponse.Merge(dst, src)
}
func (m *GanResponse) XXX_Size() int {
	return xxx_messageInfo_GanResponse.Size(m)
}
func (m *GanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GanResponse proto.InternalMessageInfo

func (m *GanResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

// Checkpoint is a struct storing weights and biases
type Checkpoint struct {
	// weights stores different weights against a string label
	Weights map[string]*Variable `protobuf:"bytes,1,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// biases stores different biases against a string label
	Biases               map[string]*Variable `protobuf:"bytes,2,rep,name=biases,proto3" json:"biases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{9}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (dst *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(dst, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetWeights() map[string]*Variable {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *Checkpoint) GetBiases() map[string]*Variable {
	if m != nil {
		return m.Biases
	}
	return nil
}

// Variable is basically a buffer and its size
type Variable struct {
	Data                 []float32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Size                 []int64   `protobuf:"varint,2,rep,packed,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e955d0adb755ecf8, []int{10}
}
func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (dst *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(dst, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Variable) GetSize() []int64 {
	if m != nil {
		return m.Size
	}
	return nil
}

func init() {
	proto.RegisterType((*EmailRequest)(nil), "api.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "api.EmailResponse")
	proto.RegisterMapType((map[string]*ListOfString)(nil), "api.EmailResponse.HeadersEntry")
	proto.RegisterType((*ListOfString)(nil), "api.ListOfString")
	proto.RegisterType((*InferImageRequest)(nil), "api.InferImageRequest")
	proto.RegisterType((*Image)(nil), "api.Image")
	proto.RegisterType((*InferImageResponse)(nil), "api.InferImageResponse")
	proto.RegisterType((*InferOutput)(nil), "api.InferOutput")
	proto.RegisterType((*GanRequest)(nil), "api.GanRequest")
	proto.RegisterType((*GanResponse)(nil), "api.GanResponse")
	proto.RegisterType((*Checkpoint)(nil), "api.Checkpoint")
	proto.RegisterMapType((map[string]*Variable)(nil), "api.Checkpoint.BiasesEntry")
	proto.RegisterMapType((map[string]*Variable)(nil), "api.Checkpoint.WeightsEntry")
	proto.RegisterType((*Variable)(nil), "api.Variable")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LambdaClient is the client API for Lambda service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LambdaClient interface {
	// Email service sends email
	Email(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	// InferImage applies trained model on input image for inferring labels
	InferImage(ctx context.Context, opts ...grpc.CallOption) (Lambda_InferImageClient, error)
}

type lambdaClient struct {
	cc *grpc.ClientConn
}

func NewLambdaClient(cc *grpc.ClientConn) LambdaClient {
	return &lambdaClient{cc}
}

func (c *lambdaClient) Email(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.Lambda/Email", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lambdaClient) InferImage(ctx context.Context, opts ...grpc.CallOption) (Lambda_InferImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lambda_serviceDesc.Streams[0], "/api.Lambda/InferImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &lambdaInferImageClient{stream}
	return x, nil
}

type Lambda_InferImageClient interface {
	Send(*InferImageRequest) error
	CloseAndRecv() (*InferImageResponse, error)
	grpc.ClientStream
}

type lambdaInferImageClient struct {
	grpc.ClientStream
}

func (x *lambdaInferImageClient) Send(m *InferImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lambdaInferImageClient) CloseAndRecv() (*InferImageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InferImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LambdaServer is the server API for Lambda service.
type LambdaServer interface {
	// Email service sends email
	Email(context.Context, *EmailRequest) (*EmailResponse, error)
	// InferImage applies trained model on input image for inferring labels
	InferImage(Lambda_InferImageServer) error
}

func RegisterLambdaServer(s *grpc.Server, srv LambdaServer) {
	s.RegisterService(&_Lambda_serviceDesc, srv)
}

func _Lambda_Email_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).Email(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Lambda/Email",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).Email(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lambda_InferImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LambdaServer).InferImage(&lambdaInferImageServer{stream})
}

type Lambda_InferImageServer interface {
	SendAndClose(*InferImageResponse) error
	Recv() (*InferImageRequest, error)
	grpc.ServerStream
}

type lambdaInferImageServer struct {
	grpc.ServerStream
}

func (x *lambdaInferImageServer) SendAndClose(m *InferImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lambdaInferImageServer) Recv() (*InferImageRequest, error) {
	m := new(InferImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Lambda_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Lambda",
	HandlerType: (*LambdaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Email",
			Handler:    _Lambda_Email_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InferImage",
			Handler:       _Lambda_InferImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	// GAN generator
	Gan(ctx context.Context, in *GanRequest, opts ...grpc.CallOption) (Api_GanClient, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Gan(ctx context.Context, in *GanRequest, opts ...grpc.CallOption) (Api_GanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Api_serviceDesc.Streams[0], "/api.Api/Gan", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GanClient interface {
	Recv() (*GanResponse, error)
	grpc.ClientStream
}

type apiGanClient struct {
	grpc.ClientStream
}

func (x *apiGanClient) Recv() (*GanResponse, error) {
	m := new(GanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	// GAN generator
	Gan(*GanRequest, Api_GanServer) error
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Gan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).Gan(m, &apiGanServer{stream})
}

type Api_GanServer interface {
	Send(*GanResponse) error
	grpc.ServerStream
}

type apiGanServer struct {
	grpc.ServerStream
}

func (x *apiGanServer) Send(m *GanResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Gan",
			Handler:       _Api_Gan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_e955d0adb755ecf8) }

var fileDescriptor_api_e955d0adb755ecf8 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xef, 0x4e, 0xd4, 0x4e,
	0x14, 0xfd, 0x75, 0xcb, 0xee, 0xb2, 0xb7, 0x25, 0x3f, 0x98, 0x10, 0xa9, 0x8b, 0x86, 0x4d, 0x31,
	0x71, 0x63, 0xcc, 0x8a, 0x4b, 0x62, 0xd4, 0x4f, 0x22, 0x21, 0x40, 0x82, 0x92, 0xd4, 0x04, 0xe3,
	0x27, 0x32, 0xdd, 0xce, 0xc2, 0x48, 0xdb, 0xa9, 0x9d, 0x29, 0x66, 0x35, 0xbe, 0x82, 0x4f, 0xe2,
	0xb3, 0xf8, 0x4c, 0x66, 0xee, 0x4c, 0xd9, 0x22, 0x24, 0x9a, 0xf8, 0x6d, 0xe6, 0x9c, 0x73, 0xff,
	0xcc, 0xb9, 0xb7, 0x85, 0x1e, 0x2d, 0xf8, 0xa8, 0x28, 0x85, 0x12, 0xc4, 0xa5, 0x05, 0x0f, 0x7f,
	0x38, 0xe0, 0xef, 0x65, 0x94, 0xa7, 0x11, 0xfb, 0x54, 0x31, 0xa9, 0xc8, 0x5d, 0x58, 0x54, 0xe2,
	0x94, 0x69, 0x28, 0x70, 0x06, 0xce, 0xb0, 0x17, 0x75, 0x95, 0x40, 0x05, 0x59, 0x83, 0xae, 0x12,
	0xa7, 0x39, 0xcd, 0x58, 0xd0, 0x42, 0xa6, 0xa3, 0xc4, 0x5b, 0x9a, 0x31, 0x72, 0x1f, 0x60, 0x5a,
	0x8a, 0xcc, 0x46, 0xb9, 0xc8, 0xf5, 0x34, 0x62, 0xe2, 0xd6, 0x01, 0x2f, 0x26, 0x72, 0x01, 0xd9,
	0x45, 0x0d, 0x60, 0x6c, 0x00, 0x5d, 0x59, 0xc5, 0x1f, 0xd9, 0x44, 0x05, 0x6d, 0x53, 0xce, 0x5e,
	0x09, 0x81, 0x85, 0x58, 0x24, 0xb3, 0xa0, 0x33, 0x70, 0x86, 0x7e, 0x84, 0xe7, 0xf0, 0xa7, 0x03,
	0x4b, 0xb6, 0x5d, 0x59, 0x88, 0x5c, 0x32, 0xb2, 0x01, 0x9e, 0x54, 0x54, 0x55, 0xf2, 0x74, 0x22,
	0x12, 0x86, 0x2d, 0xbb, 0x11, 0x18, 0x68, 0x57, 0x24, 0xec, 0x2a, 0x8d, 0x69, 0x19, 0xcf, 0xe4,
	0x05, 0x74, 0xcf, 0x19, 0x4d, 0x58, 0x29, 0x03, 0x77, 0xe0, 0x0e, 0xbd, 0xf1, 0xc6, 0x48, 0xfb,
	0x72, 0x2d, 0xf3, 0xe8, 0xc0, 0x28, 0xf6, 0x72, 0x55, 0xce, 0xa2, 0x5a, 0xdf, 0x7f, 0x03, 0x7e,
	0x93, 0x20, 0xcb, 0xe0, 0x5e, 0xb0, 0x99, 0xb5, 0x4a, 0x1f, 0xc9, 0x43, 0x68, 0x5f, 0xd2, 0xb4,
	0x32, 0x26, 0x79, 0xe3, 0x15, 0x4c, 0x7d, 0xc4, 0xa5, 0x3a, 0x9e, 0xbe, 0x53, 0x25, 0xcf, 0xcf,
	0x22, 0xc3, 0xbf, 0x6c, 0x3d, 0x77, 0xc2, 0x07, 0xe0, 0x37, 0x29, 0xb2, 0x5a, 0x07, 0x3b, 0x03,
	0x77, 0xd8, 0xb3, 0xca, 0xf0, 0x2b, 0xac, 0x1c, 0xe6, 0x53, 0x56, 0x1e, 0x66, 0xf4, 0x8c, 0xd5,
	0x93, 0x0a, 0xa1, 0xc3, 0xf5, 0x5d, 0xa2, 0xd6, 0x1b, 0x03, 0x16, 0x32, 0x12, 0xcb, 0xe8, 0xc9,
	0x64, 0x22, 0x61, 0x69, 0x73, 0x6a, 0x3d, 0x44, 0xd0, 0xfc, 0x4d, 0x58, 0x32, 0xf4, 0x25, 0x2b,
	0x25, 0x17, 0xb9, 0x9d, 0x9d, 0x8f, 0xe0, 0x89, 0xc1, 0xc2, 0x27, 0xd0, 0xc6, 0xa4, 0xda, 0x49,
	0x4c, 0x63, 0xde, 0x8a, 0x67, 0x8d, 0x25, 0x54, 0x51, 0x4c, 0xed, 0x47, 0x78, 0x0e, 0x5f, 0x01,
	0x69, 0x76, 0x6b, 0x07, 0xf5, 0x08, 0xba, 0xa2, 0x52, 0x45, 0xa5, 0xea, 0x7e, 0x97, 0x4d, 0xbf,
	0x5a, 0x79, 0x8c, 0x44, 0x54, 0x0b, 0xc2, 0x0f, 0xe0, 0x35, 0xf0, 0x5b, 0x0b, 0xaf, 0x42, 0x3b,
	0xa5, 0x31, 0x4b, 0xed, 0xa3, 0xcc, 0x85, 0x0c, 0xc0, 0x2b, 0x4a, 0x11, 0xd3, 0x98, 0xa7, 0x5c,
	0xcd, 0xf0, 0x39, 0x6e, 0xd4, 0x84, 0xc2, 0x29, 0xc0, 0x3e, 0xcd, 0x6b, 0x0f, 0xaf, 0xfb, 0xe3,
	0xfc, 0xd1, 0x9f, 0xd6, 0x4d, 0x7f, 0x74, 0x27, 0x13, 0x51, 0xe5, 0xca, 0x56, 0x33, 0x97, 0xf0,
	0x29, 0x78, 0x58, 0xc7, 0xbe, 0xfe, 0x2f, 0x86, 0x15, 0x7e, 0x6f, 0x01, 0xec, 0x9e, 0xb3, 0xc9,
	0x45, 0x21, 0x78, 0xae, 0xc8, 0x33, 0xe8, 0x7e, 0x66, 0xfc, 0xec, 0xfc, 0xca, 0xb0, 0x7b, 0x18,
	0x33, 0x57, 0x8c, 0xde, 0x1b, 0xda, 0x6e, 0xa8, 0x15, 0x93, 0x6d, 0xe8, 0xc4, 0x9c, 0x4a, 0x26,
	0x83, 0x16, 0x86, 0xad, 0xff, 0x1e, 0xf6, 0x1a, 0x59, 0x13, 0x65, 0xa5, 0xfd, 0x43, 0xf0, 0x9b,
	0xd9, 0x6e, 0x59, 0xeb, 0xcd, 0xeb, 0x6b, 0xbd, 0x84, 0x59, 0x4f, 0x68, 0xc9, 0x69, 0x9c, 0xb2,
	0xc6, 0x4a, 0xf7, 0x0f, 0xc0, 0x6b, 0x54, 0xf8, 0x87, 0x4c, 0xe1, 0x18, 0x16, 0x6b, 0xf8, 0x6a,
	0xd1, 0xb4, 0x15, 0x2d, 0xb3, 0x68, 0x1a, 0x93, 0xfc, 0x0b, 0xc3, 0x77, 0xba, 0x11, 0x9e, 0xc7,
	0xdf, 0xa0, 0x73, 0x44, 0xb3, 0x38, 0xa1, 0x64, 0x0b, 0xda, 0xe6, 0xff, 0xb3, 0xd2, 0xfc, 0xb8,
	0x71, 0xee, 0x7d, 0x72, 0xf3, 0x7b, 0x0f, 0xff, 0x23, 0x3b, 0x00, 0xf3, 0xc5, 0x25, 0x77, 0xe6,
	0xfb, 0xd9, 0xfc, 0xee, 0xfa, 0x6b, 0x37, 0xf0, 0x3a, 0xc1, 0xd0, 0x19, 0x6f, 0x83, 0xbb, 0x53,
	0x70, 0xf2, 0x18, 0xdc, 0x7d, 0x9a, 0x93, 0xff, 0x51, 0x3a, 0xdf, 0xb7, 0xfe, 0xf2, 0x1c, 0xa8,
	0x83, 0xb6, 0x9c, 0xb8, 0x83, 0x3f, 0xe4, 0xed, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x65, 0xca,
	0xc8, 0x0a, 0x9d, 0x05, 0x00, 0x00,
}
